- capstone_2024_20/Source/capstone_2024_20/Event/Event.cpp
- capstone_2024_20/Source/capstone_2024_20/Event/Event.h
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.h
이벤트 스폰 임시 로직 추가
상호작용의 경우 Character에 관련 로직 추가가 필요하여 보류
-> 다른 일감에서 작업 예정
> CSS-39 [프로그램][신규] 스테이지_이벤트_스폰

- capstone_2024_20/Source/capstone_2024_20/Enemy/Enemy.cpp
- capstone_2024_20/Source/capstone_2024_20/Enemy/Enemy.h
- capstone_2024_20/Source/capstone_2024_20/EnemyShip/EnemyShip.cpp
- capstone_2024_20/Source/capstone_2024_20/EnemyShip/EnemyShip.h
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.h
Enemy 클래스 추가
Enemy 생성 로직 추가, 임시 Mesh 및 Period 사용
> CSS-113 [프로그램][신규] 항해_적

- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.h
재화 및 관련 API 추가
테스트 코드 제거
개발 중 dev에 Rebase함
> CSS-86 [프로그램][신규] 항해_재화

- capstone_2024_20/Source/capstone_2024_20/Common/HP.cpp
- capstone_2024_20/Source/capstone_2024_20/Common/HP.h
- capstone_2024_20/Source/capstone_2024_20/Enemy/Enemy.h
> CSS-92 [프로그램][신규] 적_체력

- capstone_2024_20/Source/capstone_2024_20/MyCannon.cpp
- capstone_2024_20/Source/capstone_2024_20/MyCannon.h
- capstone_2024_20/Source/capstone_2024_20/MyPlayerController.cpp
- capstone_2024_20/Source/capstone_2024_20/MyPlayerController.h
> 대포 장전 여부 동기화

- capstone_2024_20/Source/capstone_2024_20/MyObject.cpp
SetActorRotation에서 SetActorRelativeRotation으로 변경
> 배 회전 시 다른 오브젝트들도 같이 회전되는 현상 수정

- capstone_2024_20/Source/capstone_2024_20/MyShip.cpp
- capstone_2024_20/Source/capstone_2024_20/MyShip.h
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.h
- capstone_2024_20/Source/capstone_2024_20/ShipControlStrategy.cpp
- capstone_2024_20/Source/capstone_2024_20/ShipControlStrategy.h
배 업그레이드 API 구현
MoveSpeed를 ControlStrategy에서 MyShip으로 이동
High Level인 Sailing System에서 호출하여 사용
> CSS-89 [프로그램][신규] 항해_배_업그레이드

- capstone_2024_20/Source/capstone_2024_20/Event/Event.cpp
- capstone_2024_20/Source/capstone_2024_20/Event/Event.h
- capstone_2024_20/Source/capstone_2024_20/MyObject.cpp
- capstone_2024_20/Source/capstone_2024_20/MyObject.h
- capstone_2024_20/Source/capstone_2024_20/MyPlayerController.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
이벤트 상호작용 및 MyObject 인터페이스 구현
이벤트 생성 알고리즘 일부 수정
> CSS-88 [프로그램][신규] 항해_이벤트_상호작용

- capstone_2024_20/Source/capstone_2024_20/Enemy/Enemy.cpp
- capstone_2024_20/Source/capstone_2024_20/Enemy/Enemy.h
- capstone_2024_20/Source/capstone_2024_20/EnemyShip/EnemyShip.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.h
적 생성 알고리즘 일부 수정
적 이동 로직 구현, 임시 로직으로 0번 해적을 향하도록 함
> CSS-124 [프로그램][신규] 항해_적_해적을 향해 이동 

- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.h
- capstone_2024_20/Source/capstone_2024_20/Trigger/Trigger.cpp
- capstone_2024_20/Source/capstone_2024_20/Trigger/Trigger.h
SailingSystem의 Ticking에서 플레이 타임과 클리어 여부를 검사하도록 작성
Trigger를 검사할 때 객체 참조를 위해 std::functional을 사용하도록 수정
클리어 트리거 통과 시 UI 표기 로직 추가
> CSS-90 [프로그램][신규] 항해_결과

- capstone_2024_20/Source/capstone_2024_20/Map/Obstacle.cpp
- capstone_2024_20/Source/capstone_2024_20/Map/Obstacle.h
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.h
맵에 생성할 장애물 Actor 추가 - 향후 Blueprint로 변경
맵 생성 임시 로직 추가
> CSS-123 [프로그램][신규] 항해_맵_생성 알고리즘 

- capstone_2024_20/Source/capstone_2024_20/Map/Grid.cpp
- capstone_2024_20/Source/capstone_2024_20/Map/Grid.h
- capstone_2024_20/Source/capstone_2024_20/Map/Map.cpp
- capstone_2024_20/Source/capstone_2024_20/Map/Map.h
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.h
Cellular Automata를 사용한 맵 생성 알고리즘 구현
> CSS-158 [프로그램][개선] 항해_맵 생성 알고리즘 

- capstone_2024_20/Source/capstone_2024_20/EnemyShip/EnemyShip.cpp
- capstone_2024_20/Source/capstone_2024_20/EnemyShip/EnemyShip.h
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
적 배의 생성/파괴/위치/회전각 동기화, ReplicatedActor 사용
> CSS-159 [프로그램][신규] 항해_적 배_동기화

- capstone_2024_20/Config/DefaultEngine.ini
- capstone_2024_20/Source/capstone_2024_20/Enemy/Enemy.h
- capstone_2024_20/Source/capstone_2024_20/MyCharacter.cpp
- capstone_2024_20/Source/capstone_2024_20/MyCharacter.h
- capstone_2024_20/Source/capstone_2024_20/MyPlayerController.cpp
- capstone_2024_20/Source/capstone_2024_20/MyPlayerController.h
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.h
해적 Replicated Property 추가
플레이어의 레벨 입장 시간 차이를 고려해 매 프레임마다 참조하는 해적을 다시 찾도록 작성
가까이 있는 적을 찾는 함수를 MultiCast로 작성하여, 서버에서 실행할 수 있도록 함
공격 및 처치 동기화
> CSS-189 [프로그램][신규] 항해_적_동기화

- capstone_2024_20/Config/DefaultEngine.ini
- capstone_2024_20/Source/capstone_2024_20/Enemy/Enemy.cpp
- capstone_2024_20/Source/capstone_2024_20/Enemy/Enemy.h
- capstone_2024_20/Source/capstone_2024_20/Event/Event.cpp
- capstone_2024_20/Source/capstone_2024_20/Event/Event.h
> CSS-213 [프로그램][신규] 항해_모델 적용

- capstone_2024_20/Source/capstone_2024_20/01_Network/ReplicatedCharacter.cpp
- capstone_2024_20/Source/capstone_2024_20/01_Network/ReplicatedCharacter.h
- capstone_2024_20/Source/capstone_2024_20/Enemy/Enemy.h
ReplicatedCharacter 클래스 추가, Enemy 부모 클래스 수정
> CSS-221 [프로그램][개선] 항해_적_Character 기반으로 수정 

- capstone_2024_20/Source/capstone_2024_20/EnemyShip/EnemyShip.cpp
- capstone_2024_20/Source/capstone_2024_20/EnemyShip/EnemyShip.h
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
EnemyShip에 적 스폰 가능 여부를 확인하는 변수를 추가, 적 스폰 시 이를 사용하여 검증하도록 작성
> CSS-225 [프로그램][개선] 항해_적 배_ES_0001_적을 스폰하지 않도록 수정

- capstone_2024_20/Source/capstone_2024_20/Enemy/Enemy.cpp
- capstone_2024_20/Source/capstone_2024_20/Enemy/Enemy.h
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.h
> CSS-227 [프로그램][신규] 항해_적_공격 

- capstone_2024_20/Source/capstone_2024_20/CharacterControlStrategy.cpp
- capstone_2024_20/Source/capstone_2024_20/MyCharacter.cpp
- capstone_2024_20/Source/capstone_2024_20/MyCharacter.h
- capstone_2024_20/Source/capstone_2024_20/MyPlayerController.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.h
해적의 체력이 0이 되었을 때, 키 입력(이동, 공격, 상호작용) 불가하며 적이 더 이상 공격하지 않도록 작성
> CSS-228 [프로그램][신규] 항해_해적_사망

- capstone_2024_20/Source/capstone_2024_20/Common/HP.cpp
- capstone_2024_20/Source/capstone_2024_20/Common/HP.h
- capstone_2024_20/Source/capstone_2024_20/MyCharacter.cpp
- capstone_2024_20/Source/capstone_2024_20/MyCharacter.h
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
> CSS-228 [프로그램][신규] 항해_해적_부활

- capstone_2024_20/Source/capstone_2024_20/MyPlayerController.cpp
Cannon 상호작용 전에 Bed나 Ship과 상호작용 시 버그가 발생하는 문제 해결
> [CSS-276] 상호작용 버그 수정

- capstone_2024_20/Source/capstone_2024_20/Event/Event.cpp
- capstone_2024_20/Source/capstone_2024_20/Event/Event.h
- capstone_2024_20/Source/capstone_2024_20/MyShip.cpp
- capstone_2024_20/Source/capstone_2024_20/MyShip.h
- capstone_2024_20/Source/capstone_2024_20/Object/EnemyShipCannonBall.cpp
- capstone_2024_20/Source/capstone_2024_20/Object/EnemyShipCannonBall.h
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.h
화재 이벤트를 방치하면 특정 주기마다 배에 데미지를 입히도록 작성
이때, 클라이언트에서 단독으로 계산하는 부분을 발견하여 서버로 이관
* 커밋 로그 중 CSS-261로 작성된 내용이 있으나, 실제로는 모두 CSS-262의 내용이며 로그의 제목이 잘못 기재되었음
> CSS-262 [프로그램][신규] 항해_이벤트_데미지 

- capstone_2024_20/Source/capstone_2024_20/EnemyShip/EnemyShip.cpp
- capstone_2024_20/Source/capstone_2024_20/EnemyShip/EnemyShip.h
- capstone_2024_20/Source/capstone_2024_20/MyCannon.cpp
- capstone_2024_20/Source/capstone_2024_20/MyCannon.h
> [CSS-294] cpp에 있던 헤더 헤더로 이동

- capstone_2024_20/Source/capstone_2024_20/EnemyShip/EnemyShip.cpp
> CSS-314 [QA] 항해_적 배_배를 통과하는 문제

- capstone_2024_20/Source/capstone_2024_20/Event/Event.cpp
- capstone_2024_20/Source/capstone_2024_20/Event/Event.h
- capstone_2024_20/Source/capstone_2024_20/MyObject.cpp
- capstone_2024_20/Source/capstone_2024_20/MyObject.h
- capstone_2024_20/Source/capstone_2024_20/MyPlayerController.cpp
- capstone_2024_20/Source/capstone_2024_20/MyPlayerController.h
서버에서 실행해야하는 오브젝트의 작동 로직을 위한 함수를 추가하여, 이벤트에서 사용
이때, Server RPC를 Autority가 없는 Actor에서 호출할 수 없어, 관련 함수를 PlayerController에 추가
> CSS-299 [QA] 클라이언트에서 Event와 상호작용 하였을 때, 작동하지 않는 문제

- README.md
- index.md
> Smh3223 patch 3

- capstone_2024_20/Source/capstone_2024_20/MyShip.cpp
- capstone_2024_20/Source/capstone_2024_20/MyShip.h
> CSS-354 [QA] 재화 UI가 서버-클라이언트 사이 동기화되지 않는 문제

- capstone_2024_20/Source/capstone_2024_20/MyCharacter.cpp
AnimInstance 참조를 Tick에서 하도록 변경
> CSS-356 [QA] 항해_해적_클라이언트에서 2, 3번 캐릭터가 공격 시 크래시가 일어나는 문제

- capstone_2024_20/Source/capstone_2024_20/Enemy/Enemy.cpp
- capstone_2024_20/Source/capstone_2024_20/Enemy/Enemy.h
적의 AnimInstance를 사용할 때 마다 참조하도록 작성
> CSS-356 [QA] AnimInstace 참조의 오작동으로 크래시가 일어나는 문제

- capstone_2024_20/Source/capstone_2024_20/MyShip.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.cpp
- capstone_2024_20/Source/capstone_2024_20/Sailing/SailingSystem.h
배 체력 5->20, 시작 재화 10000->0, 적 처치 재화 100->3000
정상적으로 동기화되지 않던 Currency 관련 로직 수정
> CSS-358 [프로그램][개선] 수치 조정
